#!/bin/bash

# Dotfiles root directory (automatically set if not provided)
export DOTS="${DOTS:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"

# Load configuration
source "$DOTS/init/dots.conf"

# Function to install Tmux plugins
install() {
  echo "Installing..."
  $INIT_PATH/install.sh $@
}

# Function to install Tmux plugins
uninstall() {
  $INIT_PATH/uninstall.sh $@
}

help() {
  echo "usage: $0 {install|uninstall} --{all}"
  echo "  install:            install config files for configuring the computer."
  echo "  uninstall:          uninstall all config along with tools"
  exit 1
}

# # Second argument script logic
# case "$2" in
# --all)
#   tools=true
#   ;;
# --*)
#   help
#   ;;
# esac

# Main script logic
case "$1" in
install)
  shift 1
  install $@
  ;;
uninstall)
  shift 1
  uninstall $@
  ;;
# update)
#   update # Note supported right now but coming soon
#   ;;
*)
  help
  ;;
esac
