#!/bin/bash


# Dotfiles root directory (automatically set if not provided)
export DOTS="${DOTS:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"

# Load configuration
source "$DOTS/init/dots.conf"

# Function to install Tmux plugins
install() {
  echo $tools
  if [ "$tools" == "true" ]; then
    echo "Installing configs and tools..."
    $INIT_PATH/install.sh --all
  else
    echo "Installing configs..."
    $INIT_PATH/install.sh
  fi
  e_separator
}

# Function to install Tmux plugins
uninstall() {
    $INIT_PATH/uninstall.sh
}


help(){
    echo "usage: $0 {install|uninstall} --{all}"
    echo "  install:            install config files for configuring the computer."
    echo "  uninstall:          uninstall all config along with tools"
    echo "  install --all:      install config files along with the tools"
    exit 1
}

# Second argument script logic
case "$2" in
  --all)
    tools=true
    ;;
  --*)
    help
    ;;
esac

# Main script logic
case "$1" in
  install)
    install
    ;;
  uninstall)
    uninstall
    ;;
  update)
    update # Note supported right now but coming soon
    ;;
  *)
    help
    ;;
esac

