-- return {
-- "williamboman/mason.nvim",
--     cmd = "Mason",
--     keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
--     build = ":MasonUpdate",
--     opts_extend = { "ensure_installed" },
--     opts = {
--       ensure_installed = {
--         "stylua",
--         "shfmt",
--       },
--     },
--     ---@param opts MasonSettings | {ensure_installed: string[]}
--     config = function(_, opts)
--       require("mason").setup(opts)
--       local mr = require("mason-registry")
--       mr:on("package:install:success", function()
--         vim.defer_fn(function()
--           -- trigger FileType event to possibly load this newly installed LSP server
--           require("lazy.core.handler.event").trigger({
--             event = "FileType",
--             buf = vim.api.nvim_get_current_buf(),
--           })
--         end, 100)
--       end)
--
--       mr.refresh(function()
--         for _, tool in ipairs(opts.ensure_installed) do
--           local p = mr.get_package(tool)
--           if not p:is_installed() then
--             p:install()
--           end
--         end
--       end)
--     end,
--   }

-- {
--   'WhoIsSethDaniel/mason-tool-installer.nvim',
--   event = { 'BufReadPre', 'BufNewFile' },
--   opts = {
--
--     ensure_installed = {
--       -- "prettier", -- prettier formatter
--       {
--         'stylua', -- lua formatter
--         version = 'v2.0.2',
--       },
--       -- "isort", -- python formatter
--       -- "black", -- python formatter
--       -- 'mypy', -- python linter
--       -- "pylint",
--       -- "eslint_d",
--     },
--     auto_update = false,
--     run_on_start = true,
--
--   }
-- },
return {
  -- 'williamboman/mason.nvim',
  -- -- cmd = 'Mason',
  -- -- keys = { { '<leader>cm', '<cmd>Mason<cr>', desc = 'Mason' } },
  -- -- build = ':MasonUpdate',
  -- dependencies = {
  --   'williamboman/mason-lspconfig.nvim',
  --   'WhoIsSethDaniel/mason-tool-installer.nvim',
  -- },
  -- config = function()
  --   -- import mason
  --   local mason = require 'mason'
  --
  --   -- import mason-lspconfig
  --   local mason_lspconfig = require 'mason-lspconfig'
  --   local mason_tool_installer = require 'mason-tool-installer'
  --
  --   -- enable mason and configure icons
  --   mason.setup {
  --     ui = {
  --       icons = {
  --         package_installed = '✓',
  --         package_pending = '➜',
  --         package_uninstalled = '✗',
  --       },
  --     },
  --   }
  --
  --   mason_lspconfig.setup {
  --     -- list of servers for mason to install
  --     ensure_installed = {
  --       -- "tsserver",
  --       -- "html",
  --       -- "cssls",
  --       -- "tailwindcss",
  --       -- "svelte",
  --       'lua_ls',
  --       -- "graphql",
  --       -- "emmet_ls",
  --       -- "prismals",
  --       -- "pyright",
  --     },
  --   }
  --
  --   mason_tool_installer.setup {
  --     ensure_installed = {
  --       -- "prettier", -- prettier formatter
  --       {
  --         'stylua', -- lua formatter
  --         version = 'v2.0.2',
  --       },
  --       -- "isort", -- python formatter
  --       -- "black", -- python formatter
  --       -- 'mypy', -- python linter
  --       -- "pylint",
  --       -- "eslint_d",
  --     },
  --   }
  -- end,
}
